/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package id.ac.polban.jtk.oop;

/**
 *
 * @author mufidjamaluddin
 */
public class TemplateEmail 
{
    public static String getEmailContent(String email)
    {
        String pesan = String.join(" ", "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n",
"<html xmlns=\"http://www.w3.org/1999/xhtml\">\n",
"  <head>\n",
"    <title>Pendaftaran</title>\n" ,
"    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\" />\n",
"    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\" />\n",
"    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0 \" />\n",
"    <meta name=\"format-detection\" content=\"telephone=no\" />\n",
"    <!--[if !mso]><!-->\n",
"    <link href=\"https://fonts.googleapis.com/css?family=Open,Sans:300,400,600,700\" rel=\"stylesheet\" />\n",
"    <!--<![endif]-->\n",
"    <style type=\"text/css\">\n",
"      body {\n",
"      -webkit-text-size-adjust: 100% !important;\n" ,
"      -ms-text-size-adjust: 100% !important;\n" ,
"      -webkit-font-smoothing: antialiased !important;\n" ,
"      }\n" ,
"      img {\n" ,
"      border: 0 !important;\n",
"      outline: none !important;\n" ,
"      }\n" ,
"      p {\n" ,
"      Margin: 0px !important;\n" ,
"      Padding: 0px !important;\n" ,
"      }\n" ,
"      table {\n" ,
"      border-collapse: collapse;\n" ,
"      mso-table-lspace: 0px;\n" ,
"      mso-table-rspace: 0px;\n" ,
"      }\n" ,
"      td, a, span {\n" ,
"      border-collapse: collapse;\n" ,
"      mso-line-height-rule: exactly;\n" ,
"      }\n" ,
"      .ExternalClass * {\n" ,
"      line-height: 100%;\n" ,
"      }\n" ,
"      span.MsoHyperlink {\n" ,
"      mso-style-priority:99;\n" ,
"      color:inherit;}\n" ,
"      span.MsoHyperlinkFollowed {\n" ,
"      mso-style-priority:99;\n" ,
"      color:inherit;}\n" ,
"      </style>\n" ,
"      <style media=\"only screen and (min-width:481px) and (max-width:599px)\" type=\"text/css\">\n" ,
"      @media only screen and (min-width:481px) and (max-width:599px) {\n" ,
"      table[class=em_main_table] {\n" ,
"      width: 100% !important;\n" ,
"      }\n" ,
"      table[class=em_wrapper] {\n" ,
"      width: 100% !important;\n" ,
"      }\n" ,
"      td[class=em_hide], br[class=em_hide] {\n" ,
"      display: none !important;\n" ,
"      }\n" ,
"      img[class=em_full_img] {\n" ,
"      width: 100% !important;\n" ,
"      height: auto !important;\n" ,
"      }\n" ,
"      td[class=em_align_cent] {\n" ,
"      text-align: center !important;\n" ,
"      }\n" ,
"      td[class=em_aside]{\n" ,
"      padding-left:10px !important;\n" ,
"      padding-right:10px !important;\n" ,
"      }\n" ,
"      td[class=em_height]{\n" ,
"      height: 20px !important;\n" ,
"      }\n" ,
"      td[class=em_font]{\n" ,
"      font-size:14px !important;	\n" ,
"      }\n" ,
"      td[class=em_align_cent1] {\n" ,
"      text-align: center !important;\n" ,
"      padding-bottom: 10px !important;\n" ,
"      }\n" ,
"      }\n" ,
"      </style>\n" ,
"      <style media=\"only screen and (max-width:480px)\" type=\"text/css\">\n" ,
"      @media only screen and (max-width:480px) {\n" ,
"      table[class=em_main_table] {\n" ,
"      width: 100% !important;\n" ,
"      }\n" ,
"      table[class=em_wrapper] {\n" ,
"      width: 100% !important;\n" ,
"      }\n" ,
"      td[class=em_hide], br[class=em_hide], span[class=em_hide] {\n" ,
"      display: none !important;\n" ,
"      }\n" ,
"      img[class=em_full_img] {\n" ,
"      width: 100% !important;\n" ,
"      height: auto !important;\n" ,
"      }\n" ,
"      td[class=em_align_cent] {\n" ,
"      text-align: center !important;\n" ,
"      }\n" ,
"      td[class=em_align_cent1] {\n" ,
"      text-align: center !important;\n" ,
"      padding-bottom: 10px !important;\n" ,
"      }\n" ,
"      td[class=em_height]{\n" ,
"      height: 20px !important;\n" ,
"      }\n" ,
"      td[class=em_aside]{\n" ,
"      padding-left:10px !important;\n" ,
"      padding-right:10px !important;\n" ,
"      } \n" ,
"      td[class=em_font]{\n" ,
"      font-size:14px !important;\n" ,
"      line-height:28px !important;\n" ,
"      }\n" ,
"      span[class=em_br]{\n" ,
"      display:block !important;\n" ,
"      }\n" ,
"      }\n" ,
"    </style>\n" ,
"  </head>\n" ,
"  <body style=\"margin:0px; padding:0px;\" bgcolor=\"#ffffff\">\n" ,
"    <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" bgcolor=\"#ffffff\">\n" ,
"      <!-- === PRE HEADER SECTION=== -->  \n" ,
"      <tr>\n" ,
"        <td align=\"center\" valign=\"top\"  bgcolor=\"#164efc\">\n" ,
"          <table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" class=\"em_main_table\" style=\"table-layout:fixed;\">\n" ,
"            <tr>\n" ,
"              <td style=\"line-height:0px; font-size:0px;\" width=\"600\" class=\"em_hide\" bgcolor=\"#30373b\"></td>\n" ,
"            </tr>\n" ,
"            <tr>\n" ,
"              <td valign=\"top\">\n" ,
"                <table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" class=\"em_wrapper\">\n" ,
"                  <tr>\n" ,
"                    <td height=\"10\" class=\"em_height\" style=\"font-size:1px; line-height:1px;\">&nbsp;</td>\n" ,
"                  </tr>\n" ,
"                  <tr>\n" ,
"                    <td valign=\"top\">\n" ,
"                      <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n" ,
"                        <tr>\n" ,
"                          <td valign=\"top\">\n" ,
"                            <div width=\"400\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"left\" class=\"em_wrapper\">\n" ,
"                             \n" ,
"                            </div>\n" ,
"                          </td>\n" ,
"                        </tr>\n" ,
"                      </table>\n" ,
"                    </td>\n" ,
"                  </tr>\n" ,
"                  <tr>\n" ,
"                    <td height=\"10\" class=\"em_height\" style=\"font-size:1px; line-height:1px;\">&nbsp;</td>\n" ,
"                  </tr>\n" ,
"                </table>\n" ,
"              </td>\n" ,
"            </tr>\n" ,
"          </table>\n" ,
"        </td>\n" ,
"      </tr>\n" ,
"      <!-- === //PRE HEADER SECTION=== -->  \n" ,
"      <!-- === BODY SECTION=== --> \n" ,
"      <tr>\n" ,
"        <td align=\"center\" valign=\"top\"  bgcolor=\"#ffffff\">\n" ,
"          <table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" class=\"em_main_table\" style=\"table-layout:fixed;\">\n" ,
"\n" ,
"            <tr>\n" ,
"              <td valign=\"top\" class=\"em_aside\">\n" ,
"                <table width=\"100%\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\">\n" ,
"\n" ,
"                  <tr>\n" ,
"                    <td height=\"34\" class=\"em_height\">&nbsp;</td>\n" ,
"                  </tr>\n" ,
"                  <tr>\n" ,
"                    <td style=\"font-family:'Open Sans', Arial, sans-serif; font-size:15px; line-height:22px; color:#999999;\">\n" ,
"						<p text-align=\"justify\" text-justify=\"inter-word\">\n Hai, " , email ,
"							Anda mendapatkan undangan dari izqffy@gmail.com untuk mendaftar sebagai user d Portal Tenaga Kerja di PT Oil & Gas.\n" ,
"						</p>\n" ,
                "				<p text-align=\"justify\" text-justify=\"inter-word\">\n" ,
"						" ,
"						</p>\n" ,
"						<p text-align=\"justify\" text-justify=\"inter-word\">\n" ,
"							Talentpool Oil & Gas merupakan database pekerja professional Indonesia \n" ,
"						</p>\n" ,
"                    </td>\n" ,
"                  </tr>\n" ,
"				  <tr>\n" ,
"                    <td height=\"12\" style=\"font-size:1px; line-height:1px;\">&nbsp;</td>\n" ,
"                  </tr>\n" ,
"                  <tr>\n" ,
"                    <td valign=\"top\" align=\"center\">\n" ,
"                      <table width=\"210\" border=\"0\" cellspacing=\"0\" cellpadding=\"0\" align=\"center\">\n" ,
"                          <td valign=\"middle\" align=\"center\" height=\"45\" bgcolor=\"#feae39\" style=\"font-family:'Open Sans', Arial, sans-serif; font-size:17px; font-weight:bold; color:#ffffff; text-transform:uppercase;\">Talentpool</td>\n" ,
"                        <tr>\n" ,
"                        </tr>\n" ,
"                      </table>\n" ,
"                    </td>\n" ,
"                  </tr>\n" ,
"				  <tr>\n" ,
"                    <td height=\"34\" class=\"em_height\">&nbsp;</td>\n" ,
"                  </tr>\n" ,
"                  <tr>\n" ,
"                    <td style=\"font-family:'Open Sans', Arial, sans-serif; font-size:15px; line-height:22px; color:#999999;\">\n" ,
"						<p text-align=\"justify\" text-justify=\"inter-word\">\n" ,
"							Terimakasih,\n" ,
"							<br/>\n" ,
"							Admin Portal Tenaga Kerja\n" ,
"							<br/>\n" ,
"							Untuk Pertanyaan atau penjelasan lebih lanjut dapat menghubungi email admin.talentpool@oilgas.id\n" ,
"						</p>\n" ,
"                    </td>\n" ,
"                  </tr>\n" ,
"                  <tr>\n" ,
"                    <td height=\"31\" class=\"em_height\">&nbsp;</td>\n" ,
"                  </tr>\n" ,
"                </table>\n" ,
"              </td>\n" ,
"            </tr>\n" ,
"            <!-- === //IMG WITH TEXT AND COUPEN CODE SECTION === -->\n" ,
"          </table>\n" ,
"        </td>\n" ,
"      </tr>\n" ,
"      <!-- === //BODY SECTION=== -->\n" ,
"      <!-- === FOOTER SECTION === -->\n" ,
"      <tr>\n" ,
"        <td align=\"center\" valign=\"top\"  bgcolor=\"#d3d3d3\" class=\"em_aside\">\n" ,
"          <table width=\"600\" cellpadding=\"0\" cellspacing=\"0\" border=\"0\" align=\"center\" class=\"em_main_table\" style=\"table-layout:fixed;\">\n" ,
"      \n" ,
"            <tr>\n" ,
"              <td height=\"10\" style=\"font-size:1px; line-height:1px;\">&nbsp;</td>\n" ,
"            </tr>\n" ,
"			<tr>\n" ,
"              <td align=\"center\" style=\"font-family:'Open Sans', Arial, sans-serif; font-size:12px; line-height:18px; color:#848789;text-transform:uppercase;\">\n" ,
"                Situs Resmi Lowongan Pekerjaan\n" ,
"              </td>\n" ,
"            </tr>\n" ,
"			<tr>\n" ,
"              <td height=\"10\" style=\"font-size:1px; line-height:1px;\">&nbsp;</td>\n" ,
"            </tr>\n" ,
"            <tr>\n" ,
"              <td align=\"center\" style=\"font-family:'Open Sans', Arial, sans-serif; font-size:12px; line-height:18px; color:#848789;text-transform:uppercase;\">\n" ,
"                Copyright &copy;2&zwnj;018 Gas dan Oil Company\n" ,
"              </td>\n" ,
"            </tr>\n" ,
"            <tr>\n" ,
"              <td height=\"35\" class=\"em_height\">&nbsp;</td>\n" ,
"            </tr>\n" ,
"          </table>\n" ,
"        </td>\n" ,
"      </tr>\n" ,
"      <!-- === //FOOTER SECTION === -->\n" ,
"    </table>\n" ,
"    <div style=\"display:none; white-space:nowrap; font:20px courier; color:#ffffff; background-color:#ffffff;\">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;</div>\n" ,
"  </body>\n" ,
"</html>");
        return pesan;
    }
}
